version: '3.8'

services:
  backend:
    build:
      context: ./back
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: ./front
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
